#!/usr/bin/env bash
# elect-rix deploy pipeline — build + backup + (optionally) deploy
# Usage: ./scripts/deploy.sh [--dry-run] [--no-backup]
# Author: generated by Hermes for elect-rix.tech

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT_NAME="elect-rix"
CF_TOKEN_FILE="${HOME}/.secrets/cf-token.txt"
BUILD_DIR="${PROJECT_ROOT}/dist"
BACKUP_BASE="${HOME}/.elect-rix-backups"
BACKUP_DIR="${BACKUP_BASE}/$(date +%Y%m%d-%H%M%S)"
DRY_RUN=false
NO_BACKUP=false
WRANGLER=$(command -v wrangler || echo "")
BUN=$(command -v bun || echo "")

usage() {
  cat <<'EOF'
Usage: deploy.sh [OPTIONS]

  --dry-run      Build and simulate deploy; do not push to Cloudflare
  --no-backup    Skip local dist backup (not recommended for production)
  --help         Show this message

Pipeline steps:
  1. Environment check (bun, wrangler, token)
  2. Build production dist/
  3. Validate build (index.html exists, no empty pages)
  4. Snapshot backup of dist/ to ~/.elect-rix-backups/
  5. Wrangler deploy (or dry-run simulation)
  6. Post-deploy verification (HEAD request to https://elect-rix.tech)
EOF
  exit 0
}

log()  { echo "[$(date +%H:%M:%S)] $*"; }
fail() { echo "[FATAL] $*" >&2; exit 1; }

while [[ $# -gt 0 ]]; do
  case $1 in
    --dry-run)   DRY_RUN=true; shift ;;
    --no-backup) NO_BACKUP=true; shift ;;
    --help)      usage ;;
    *)           fail "Unknown option: $1"; ;;
  esac
done

cd "${PROJECT_ROOT}"

log "=== elect-rix deploy pipeline ==="
log "Mode:      $([[ "$DRY_RUN" == true ]] && echo DRY-RUN || echo LIVE)"
log "Backup:    $([[ "$NO_BACKUP" == true ]] && echo SKIP || echo ENABLED)"

# ── 1. Environment check ──
[[ -n "$BUN" ]]      || fail "bun not found in PATH"
[[ -n "$WRANGLER" ]] || fail "wrangler not found in PATH"
[[ -f "$CF_TOKEN_FILE" ]] || fail "Cloudflare token missing: ${CF_TOKEN_FILE}"
[[ -s "$CF_TOKEN_FILE" ]] || fail "Cloudflare token empty: ${CF_TOKEN_FILE}"

log "Bun:       ${BUN}"
log "Wrangler:  ${WRANGLER}"
log "Project:   ${PROJECT_NAME}"
log "---"

# ── 2. Build ──
log "Step 2: Building production site..."
rm -rf "${BUILD_DIR}"
${BUN} install --frozen-lockfile 2>/dev/null || ${BUN} install
${BUN} run build

# ── 3. Validate ──
log "Step 3: Validating build..."
[[ -f "${BUILD_DIR}/index.html" ]] || fail "index.html missing"
[[ -f "${BUILD_DIR}/404.html" ]]   || fail "404.html missing"
[[ -s "${BUILD_DIR}/sitemap-index.xml" ]] || log "WARN: sitemap missing"
HTML_COUNT=$(find "${BUILD_DIR}" -name '*.html' | wc -l)
log "HTML pages: $HTML_COUNT"
[[ "$HTML_COUNT" -ge 5 ]] || fail "Suspiciously low page count: $HTML_COUNT"

# ── 4. Backup ──
if [[ "$NO_BACKUP" == false ]]; then
  log "Step 4: Snapshot backup to ${BACKUP_DIR}..."
  mkdir -p "${BACKUP_DIR}"
  cp -r "${BUILD_DIR}/" "${BACKUP_DIR}/"
  du -sh "${BACKUP_DIR}" | awk '{print "Backup size: "$1}'
  # Rotate backups: keep last 10
  ls -1dt "${BACKUP_BASE}"/* 2>/dev/null | tail -n +11 | xargs -r rm -rf
fi

# ── 5. Deploy ──
if [[ "$DRY_RUN" == true ]]; then
  log "Step 5: DRY-RUN wrangler pages deploy (simulated)..."
  ${WRANGLER} pages deploy "${BUILD_DIR}" --project-name="${PROJECT_NAME}" --dry-run || true
  log "DRY-RUN complete. No files pushed."
else
  log "Step 5: Deploying to Cloudflare Pages..."
  CLOUDFLARE_API_TOKEN=$(cat "${CF_TOKEN_FILE}") \
    ${WRANGLER} pages deploy "${BUILD_DIR}" --project-name="${PROJECT_NAME}"
fi

# ── 6. Post-deploy verify ──
if [[ "$DRY_RUN" == false ]]; then
  log "Step 6: Verifying live site..."
  for url in "https://elect-rix.tech" "https://elect-rix.tech/404.html"; do
    HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" --max-time 15 "$url" || echo "000")
    if [[ "$HTTP_CODE" == "200" || "$HTTP_CODE" == "404" ]]; then
      log "  $url => $HTTP_CODE OK"
    else
      log "  $url => $HTTP_CODE FAIL"
    fi
  done
fi

log "=== Pipeline complete ==="
